server:
  port: 8900

spring:
  application:
    name: provider

eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka

logging:
  level:
    root: INFO   